### ISSUE TITLE
Support for input streams

### ISSUE THREAD

**Issue by AdrianPhil** [sprylab/xar#10]
Hi,

I'm using this library and it does a great job so far.  In some cases my archived data does not come from a file but from other sources that expose an inputStream. Would it be possible to add an overloaded XarFile constructor that take an Input stream so I can support these other cases. I see you are using an InputStream internally later on but it's not visible.

Thank you very much,
Adrian

**Comment by hameno** [comment]
Unfortunately it's not that easy as we need random access to the data. If your other source is an http url, you can check out my pull request which adds support for streaming access over http. This requires a server with support for byte-range requests.

**Comment by hameno** [comment]
This has been implemented in 0.9.6
