### ISSUE TITLE
NPE when adding 0 byte file to archive

### ISSUE THREAD

**Issue by rzimmer** [sprylab/xar#8]
Adding a zero-sized file with name `~fiestazetec~xznl3n.idlk` to an archive causes the library to throw a NPE. It should be checked if this is a general issue with 0 byte files or if there is another reason for the NPE.

**Comment by hameno** [comment]
I believe this could be fixed with the change suggested in https://github.com/square/okio/issues/786#issuecomment-745448838 and implemented in #14
